import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Load Eudoxus Sans from /public/font/
const eudoxus = localFont({
  src: [
    {
      path: "./font/EudoxusSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/EudoxusSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./font/EudoxusSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-eudoxus",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={eudoxus.variable}>
      <body className="antialiased font-sans">{children}</body>
    </html>
  );
}
